apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-docker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-docker-app
  template:
    metadata:
      labels:
        app: dev-docker-app
    spec:
      containers:
      - name: dev-docker-app
        image: michaelatnutanix/dev-docker-app:${GIT_COMMIT}
        ports:
        - containerPort: 5000

